"""TASK-007E deployment-checkpoint handoff tests.

These tests verify provenance presentation and compatibility validation.  The
real deployment smoke is skipped on machines that do not have the local
TASK-008/TASK-009C artifacts; no checkpoint is committed or generated by the
test suite.
"""

from __future__ import annotations

import inspect
import unittest
from pathlib import Path
from tempfile import TemporaryDirectory

from visualizer.app.integration import run_headless_recognizer_queue
from visualizer.mapping import Core28Resolver
from visualizer.queue import PlaybackQueueItem
from visualizer.recognition import CheckpointCompatibilityError, RecognizerAdapter
import visualizer.recognition.adapter as adapter_module


ROOT = Path(__file__).resolve().parents[1]
RUN_ROOT = Path("/home/hatim/graduation-project-runs/task008-core28-full")
DEPLOYMENT_CHECKPOINT = Path(
    "/home/hatim/graduation-project-runs/task009c-core28-deployment/deployment.pt"
)
RESEARCH_CHECKPOINT = Path(
    "/home/hatim/graduation-project-runs/task009b-core28-lstm/"
    "full/q-absolute/masked_mean/fold01/seed1337/best.pt"
)
LABELS = ROOT / "datasets/manifests/karsl_core28_labels.csv"
MANIFEST = ROOT / "datasets/manifests/karsl_core28.csv"
CATALOG = ROOT / "visualizer/catalog/core28_exemplars.json"


class Task007EUnitTests(unittest.TestCase):
    def test_library_does_not_hardcode_deployment_machine_path(self) -> None:
        source = inspect.getsource(adapter_module)
        self.assertNotIn("task009c-core28-deployment", source)
        self.assertNotIn("/home/hatim", source)

    def test_malformed_deployment_provenance_is_rejected(self) -> None:
        if not DEPLOYMENT_CHECKPOINT.is_file():
            self.skipTest("TASK-009C deployment checkpoint is not available")
        import torch

        payload = torch.load(DEPLOYMENT_CHECKPOINT, map_location="cpu", weights_only=False)
        payload["experiment"] = dict(payload["experiment"])
        payload["experiment"]["fold"] = "01"
        with TemporaryDirectory() as temporary:
            malformed = Path(temporary) / "deployment-with-fold-mismatch.pt"
            torch.save(payload, malformed)
            with self.assertRaises(CheckpointCompatibilityError):
                RecognizerAdapter.from_checkpoint(
                    malformed,
                    run_root=RUN_ROOT,
                    labels_path=LABELS,
                )

    def test_deployment_role_is_metadata_driven_not_filename_driven(self) -> None:
        from visualizer.recognition.adapter import CheckpointMetadata

        metadata = CheckpointMetadata(
            path="/tmp/deployment.pt",
            schema_version="task009b_checkpoint_v1",
            contract_version="task009a_sequence_input_v1",
            feature_set="full",
            quaternion_policy="absolute",
            pooling="masked_mean",
            input_policy="values_and_feature_valid",
            fold="all",
            seed=1337,
            best_epoch=27,
            best_metric=0.0,
            best_metric_name="not_applicable_fixed_epoch_budget",
            input_dim=92,
            num_classes=28,
            device="cpu",
            training_role="unknown",
            training_scope="all_core28_sequences",
            training_samples=4222,
            signers=("01", "02", "03"),
        )
        self.assertEqual(metadata.provenance_kind, "unknown")
        self.assertEqual(metadata.role_display, "CHECKPOINT PROVENANCE UNKNOWN")
        self.assertIsNone(metadata.held_out_signer)
        self.assertNotIn("DEPLOYMENT MODEL", metadata.warning)

    def test_visualizer_only_mode_has_no_required_checkpoint(self) -> None:
        # This is a source-level guard for the explicit optional-checkpoint
        # contract; the real visualization-only path remains covered by the
        # TASK-007D suite when production artifacts are present.
        script = (ROOT / "scripts/run_task007d_visualizer_recognizer.py").read_text(
            encoding="utf-8"
        )
        self.assertIn('parser.add_argument("--checkpoint", type=Path, default=None', script)


@unittest.skipUnless(
    RUN_ROOT.is_dir() and DEPLOYMENT_CHECKPOINT.is_file() and LABELS.is_file(),
    "local TASK-008 and TASK-009C deployment artifacts are not available",
)
class Task007EDeploymentSmokeTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.resolver = Core28Resolver(catalog_path=CATALOG)
        cls.adapter = RecognizerAdapter.from_checkpoint(
            DEPLOYMENT_CHECKPOINT,
            run_root=RUN_ROOT,
            labels_path=LABELS,
        )

    def test_deployment_metadata_is_displayed_without_held_out_signer(self) -> None:
        metadata = self.adapter.metadata
        self.assertTrue(metadata.is_deployment)
        self.assertEqual(metadata.provenance_kind, "deployment")
        self.assertEqual(metadata.training_role, "deployment_all_signers")
        self.assertEqual(metadata.fold, "all")
        self.assertEqual(metadata.training_scope, "all_core28_sequences")
        self.assertEqual(metadata.training_samples, 4222)
        self.assertEqual(metadata.signers, ("01", "02", "03"))
        self.assertIsNone(metadata.held_out_signer)
        self.assertEqual(metadata.role_display, "DEPLOYMENT MODEL")
        self.assertIn("All Core-28 signers", metadata.training_scope_display)
        self.assertIn("4,222 training sequences", metadata.training_scope_display)
        self.assertIn("not deployment accuracy", metadata.scientific_reference_display)
        self.assertIn("67.63%", metadata.scientific_reference_display)
        self.assertIn("0.6607", metadata.scientific_reference_display)
        self.assertNotIn("held-out signer", metadata.warning)

    def test_deployment_checkpoint_predicts_four_distinct_muhammad_queue_events(self) -> None:
        result = run_headless_recognizer_queue(
            "محمد",
            run_root=RUN_ROOT,
            recognition_adapter=self.adapter,
            resolver=self.resolver,
            manifest_path=MANIFEST,
        )
        self.assertTrue(result.queue_complete)
        self.assertEqual(result.completed_indices, (0, 1, 2, 3))
        self.assertEqual([entry["character"] for entry in result.played], list("محمد"))
        self.assertEqual([entry["sign_id"] for entry in result.played], ["0055", "0037", "0055", "0039"])
        self.assertTrue(all(entry["recognition"]["available"] for entry in result.played))
        for entry in result.played:
            recognition = entry["recognition"]
            self.assertEqual(len(recognition["probabilities"]), 28)
            self.assertTrue(all(0.0 <= value <= 1.0 for value in recognition["probabilities"]))
            self.assertEqual(
                recognition["checkpoint_metadata"]["provenance_kind"],
                "deployment",
            )
            self.assertIsNone(recognition["checkpoint_metadata"]["held_out_signer"])

    def test_research_checkpoint_still_reports_loso_provenance(self) -> None:
        if not RESEARCH_CHECKPOINT.is_file():
            self.skipTest("TASK-009B research checkpoint is not available")
        adapter = RecognizerAdapter.from_checkpoint(
            RESEARCH_CHECKPOINT,
            run_root=RUN_ROOT,
            labels_path=LABELS,
        )
        self.assertTrue(adapter.metadata.is_research_loso)
        self.assertEqual(adapter.metadata.fold, "01")
        self.assertEqual(adapter.metadata.held_out_signer, "S01")
        self.assertIn("DEMO / RESEARCH CHECKPOINT", adapter.metadata.warning)
        self.assertIn("held-out signer S01", adapter.metadata.warning)
        self.assertNotEqual(adapter.metadata.provenance_kind, "deployment")


if __name__ == "__main__":
    unittest.main()
